### ISSUE TITLE
Tile ObjectGroup's not set properly if one or more tiles have no properties or objects

### ISSUE THREAD

**Issue by matthew-nagy** [SSBMTonberry/tileson#46] opened 2021-11-10 23:17 UTC
In the tileset JSON file, only tiles with properties or objects are mentioned. So it may list the tiles [1, 2, 3, 7]. When it does this, tileson puts all of tile 7's properties on objects on tile 4 instead, as it was the 4th entry in the json file. An example:
`{
         "id":1,
         "objectgroup":
            {
             "draworder":"index",
             "name":"",
             "objects":[
                    {
                     "height":32,
                     "id":1,
                     "name":"",
                     "properties":[
                            {
                             "name":"Collision",
                             "type":"string",
                             "value":"Wall,Opaque"
                            }],
                     "rotation":0,
                     "type":"",
                     "visible":true,
                     "width":32,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":3,
         "properties":[
                {
                 "name":"Example",
                 "type":"string",
                 "value":"Help, where is tile 2?"
                }]
        }`
When tileson reads in the tileset, it incorrectly put this "Example" property in tile 2's object group, and nothing in tile 3's. Were tile 3 to have a property, it would put that in tile 2's properties as well.
So far my solution has just been to add dummy properties to all my tiles, but its not ideal and was really hard to debug!

**Comment by SSBMTonberry** [comment] 2021-11-11 06:40
Thank you very much for posting this issue 🙂 
This sounds like a kinda complicated problem. Could you send me a map where this bug can be reproduced? If so I can use it in a integration test as well, if you allow it.

**Comment by matthew-nagy** [comment] 2021-11-11 17:13
[Basic Flooring.zip](https://github.com/SSBMTonberry/tileson/files/7522081/Basic.Flooring.zip)
Some of the tiles in this set have collision objects on them, others don't.
In the JSON file, objects 1-5, 8 and 12 have them, objects 6, 7, 9, 10 and 11 do not. The Json parser will put tile 8 and 12s objects in tile 6 and 7s object group respectivly.

**Comment by SSBMTonberry** [comment] 2021-11-12 14:10
Thanks, @matthew-nagy !
I'll look into this issue right away. I'll let you know when it's fixed :slightly_smiling_face:

**Comment by SSBMTonberry** [comment] 2021-11-12 14:50
@matthew-nagy: It seems like what you have included in the Basic Flooring.zip is just a Tileset definition. I would need a full Tiled map to be able to make a proper integration test, as tilesets uses data from a tson::Map to resolve things that are not presented, like tiles that have no properties, and thus are not included in Tiled's map export.

**Comment by SSBMTonberry** [comment] 2021-11-13 16:57
FYI: I've just created a map and a tileset image to represent the tileset data you provided, so you don't need to provide a map anymore :slightly_smiling_face:

**Comment by SSBMTonberry** [comment] 2021-11-14 08:59
@matthew-nagy : I've not been able to reproduce the problem. I started off with a simple integration test  to verify every object group in the tileset you provided, and the test passed, so I need some more input from you. A code example could be useful, if you've used different parts of Tileson compared to what I have used in my test. If you are able to reproduce the error using the [issue_46_map.json](https://github.com/SSBMTonberry/tileson/blob/master/content/test-maps/issues/issue_46_map.json) with a code example, that would be great. 

I have merged my integration test into master, with all the `issue_46` files I've used.
The integration test itself can be found [HERE](https://github.com/SSBMTonberry/tileson/blob/master/tests/tests_reported_issues.cpp), and goes by the name `Tile ObjectGroup's not set properly if one or more tiles have no properties or objects (Issue #46)`. Also: I did a minor change where I removed the `const`from the `getObjectgroup()` inside `tson::Tile` to make the accessibility consistent with `tson::Layer`.

Awaiting your response :slightly_smiling_face:

**Comment by matthew-nagy** [comment] 2021-11-15 10:50
Ah, sorry for not seeing that message, I am trapped in coursework-ville right now :(
I should be able to sort out my map and code by the end of the day though (UK time)

**Comment by SSBMTonberry** [comment] 2022-02-01 20:31
The content needs to be placed in the correct relative path to what the build expects. Unfortunately this differs based on what IDE you build with. Visual Studio will for instance produce several folders as a default, while CLion, that I am using, would have the output in a single folder. When the relative paths are okay, though, the tests should be fine :)

**Comment by SSBMTonberry** [comment] 2022-07-15 12:54
Closing this issue as it has been dead for quite a while, without any proof that there is an issue caused by a bug in `Tileson`. Will consider re-opening it if anything proving a bug is posted.

**Closed by SSBMTonberry** 2022-07-15 12:54 UTC
Labels: bug
