### ISSUE TITLE
tests failing using apple clang 13.0.0

### ISSUE THREAD

**Issue by dmlary** [SSBMTonberry/tileson#81] opened 2022-11-30 04:30 UTC
## Summary
Using the latest master branch, there are three tests that fail when built with Apple Clang 13.0.0.

## Details
Using commit:
```txt
commit 6572decc519ff64a674e8445a7f82d3933e689a0 (HEAD -> master, origin/master, origin/HEAD)
Author: Robin <ssbmtonberry@gmail.com>
Date:   Fri Nov 4 17:25:36 2022 +0100

    Updated README.
```

Build steps:
```sh
tileson-src> cmake -S . -B ./build -G Ninja
-- The C compiler identification is AppleClang 13.0.0.13000029
-- The CXX compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/opt/ccache/libexec/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/opt/ccache/libexec/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
OSX!
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/build
tileson-src> ninja -C ./build tileson_tests
ninja: Entering directory `./build'
[1/14] Building CXX object tests/CMakeFiles/tileson_tests.dir/tests_reported_issues.cpp.o
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_reported_issues.cpp:9:
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../tileson.hpp:6739:73: warning: '/*' within block comment [-Wcomment]
            //int                                    m_version{};       /*! 'version': The JSON format version - Removed in Tileson v1.3.0*/
                                                                        ^
1 warning generated.
[2/14] Building CXX object tests/CMakeFiles/tileson_tests.dir/tests_compression_or_encoding.cpp.o
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_compression_or_encoding.cpp:8:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson.h:36:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson_parser.hpp:47:
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tiled/Map.hpp:93:73: warning: '/*' within block comment [-Wcomment]
            //int                                    m_version{};       /*! 'version': The JSON format version - Removed in Tileson v1.3.0*/
                                                                        ^
1 warning generated.
[3/14] Building CXX object tests/CMakeFiles/tileson_tests.dir/tests_objects.cpp.o
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_objects.cpp:10:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson.h:36:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson_parser.hpp:47:
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tiled/Map.hpp:93:73: warning: '/*' within block comment [-Wcomment]
            //int                                    m_version{};       /*! 'version': The JSON format version - Removed in Tileson v1.3.0*/
                                                                        ^
1 warning generated.
[4/14] Building CXX object tests/CMakeFiles/tileson_tests.dir/tests_tiled_nlohmann.cpp.o
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_tiled_nlohmann.cpp:24:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson.h:36:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson_parser.hpp:47:
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tiled/Map.hpp:93:73: warning: '/*' within block comment [-Wcomment]
            //int                                    m_version{};       /*! 'version': The JSON format version - Removed in Tileson v1.3.0*/
                                                                        ^
1 warning generated.
[5/14] Building CXX object tests/CMakeFiles/tileson_tests.dir/tests_projects_and_worlds.cpp.o
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_projects_and_worlds.cpp:11:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson.h:36:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson_parser.hpp:47:
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tiled/Map.hpp:93:73: warning: '/*' within block comment [-Wcomment]
            //int                                    m_version{};       /*! 'version': The JSON format version - Removed in Tileson v1.3.0*/
                                                                        ^
1 warning generated.
[6/14] Building CXX object tests/CMakeFiles/tileson_tests.dir/tests_interfaces.cpp.o
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_interfaces.cpp:8:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson.h:36:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson_parser.hpp:47:
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tiled/Map.hpp:93:73: warning: '/*' within block comment [-Wcomment]
            //int                                    m_version{};       /*! 'version': The JSON format version - Removed in Tileson v1.3.0*/
                                                                        ^
1 warning generated.
[7/14] Building CXX object tests/CMakeFiles/tileson_tests.dir/tests_tiled_picojson.cpp.o
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_tiled_picojson.cpp:13:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson.h:36:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson_parser.hpp:47:
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tiled/Map.hpp:93:73: warning: '/*' within block comment [-Wcomment]
            //int                                    m_version{};       /*! 'version': The JSON format version - Removed in Tileson v1.3.0*/
                                                                        ^
1 warning generated.
[8/14] Building CXX object tests/CMakeFiles/tileson_tests.dir/tests_benchmarks.cpp.o
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_benchmarks.cpp:13:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson.h:36:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson_parser.hpp:47:
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tiled/Map.hpp:93:73: warning: '/*' within block comment [-Wcomment]
            //int                                    m_version{};       /*! 'version': The JSON format version - Removed in Tileson v1.3.0*/
                                                                        ^
1 warning generated.
[9/14] Building CXX object tests/CMakeFiles/tileson_tests.dir/tests_tiled_gason.cpp.o
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_tiled_gason.cpp:11:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson.h:36:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson_parser.hpp:47:
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tiled/Map.hpp:93:73: warning: '/*' within block comment [-Wcomment]
            //int                                    m_version{};       /*! 'version': The JSON format version - Removed in Tileson v1.3.0*/
                                                                        ^
1 warning generated.
[10/14] Building CXX object tests/CMakeFiles/tileson_tests.dir/tests_tiled_json11.cpp.o
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_tiled_json11.cpp:13:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson.h:36:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson_parser.hpp:47:
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tiled/Map.hpp:93:73: warning: '/*' within block comment [-Wcomment]
            //int                                    m_version{};       /*! 'version': The JSON format version - Removed in Tileson v1.3.0*/
                                                                        ^
1 warning generated.
[11/14] Building CXX object tests/CMakeFiles/tileson_tests.dir/tests_animation.cpp.o
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_animation.cpp:10:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson.h:36:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson_parser.hpp:47:
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tiled/Map.hpp:93:73: warning: '/*' within block comment [-Wcomment]
            //int                                    m_version{};       /*! 'version': The JSON format version - Removed in Tileson v1.3.0*/
                                                                        ^
1 warning generated.
[12/14] Building CXX object tests/CMakeFiles/tileson_tests.dir/tests_main.cpp.o
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_main.cpp:16:
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../extras/pocketlzma.hpp:6125:9: warning: 'MOVE_POS' macro redefined [-Wmacro-redefined]
#define MOVE_POS \
        ^
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../extras/pocketlzma.hpp:3587:9: note: previous definition is here
#define MOVE_POS(p, num) { \
        ^
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_main.cpp:21:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson.h:36:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson_parser.hpp:47:
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tiled/Map.hpp:93:73: warning: '/*' within block comment [-Wcomment]
            //int                                    m_version{};       /*! 'version': The JSON format version - Removed in Tileson v1.3.0*/
                                                                        ^
2 warnings generated.
[13/14] Building CXX object tests/CMakeFiles/tileson_tests.dir/tests_enums_and_classes.cpp.o
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_enums_and_classes.cpp:10:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson.h:36:
In file included from /Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tileson_parser.hpp:47:
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/../include/tiled/Map.hpp:93:73: warning: '/*' within block comment [-Wcomment]
            //int                                    m_version{};       /*! 'version': The JSON format version - Removed in Tileson v1.3.0*/
                                                                        ^
1 warning generated.
[14/14] Linking CXX executable tests/tileson_tests
```

Test output:
```txt
tileson-src/build> ./tests/tileson_tests
tileson_tests(61818,0x1059e0e00) malloc: can't allocate region
:*** mach_vm_map(size=140732882980864, flags: 100) failed (error code=3)
tileson_tests(61818,0x1059e0e00) malloc: *** set a breakpoint in malloc_error_break to debug

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tileson_tests is a Catch v2.13.8 host application.
Run with -? for options

-------------------------------------------------------------------------------
Parse a whole COMPRESSED map by file
-------------------------------------------------------------------------------
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_main.cpp:408
...............................................................................

/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_main.cpp:408: FAILED:
due to unexpected exception with message:
  std::bad_alloc

tileson_tests(61818,0x1059e0e00) malloc: can't allocate region
:*** mach_vm_map(size=140732882980864, flags: 100) failed (error code=3)
tileson_tests(61818,0x1059e0e00) malloc: *** set a breakpoint in malloc_error_break to debug
-------------------------------------------------------------------------------
Parse a whole COMPRESSED map by memory
-------------------------------------------------------------------------------
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_main.cpp:435
...............................................................................

/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_main.cpp:435: FAILED:
due to unexpected exception with message:
  std::bad_alloc

m_str: CustomValueFile not found: ../../content/test-maps/issues/issue_17.json
tileson_tests(61818,0x1059e0e00) malloc: can't allocate region
:*** mach_vm_map(size=140732882980864, flags: 100) failed (error code=3)
tileson_tests(61818,0x1059e0e00) malloc: *** set a breakpoint in malloc_error_break to debug
-------------------------------------------------------------------------------
Run benchmarks on all supported json-backends
-------------------------------------------------------------------------------
/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_benchmarks.cpp:20
...............................................................................

/Users/dmlary/src/flecs-magnum/build/_deps/tileson-src/tests/tests_benchmarks.cpp:20: FAILED:
due to unexpected exception with message:
  std::bad_alloc

===============================================================================
test cases:   98 |   95 passed | 3 failed
assertions: 1672 | 1669 passed | 3 failed
```

**Comment by SSBMTonberry** [comment] 2022-11-30 07:16
Thank you for a well described issue!

The errors looks kinda strange, but at the same time there is no `CI` test running `Clang` at the moment (due to some struggles making that work), so if there is something there, I probably wouldn't be able to catch it before the final cleanup before a release, where I personally makes sure everything works with the major compilers for `Windows`, `Linux` and `OSX`. The errors seems to be mainly caused by `benchmark` tests though, which honestly should just be optional, but this issue should be looked into nonetheless.

Will assign this to the current release so it will be looked into before the release. I'll probably get the same error when I do this myself :slightly_smiling_face:

**Comment by dmlary** [comment] 2022-11-30 13:13
So this issue is a lead up to a PR for fixing all compiler warnings (`

**Comment by SSBMTonberry** [comment] 2022-12-03 13:52
While working on the CI fix (and improvements), I've added Clang 12 and 13 for the clang builds.
I'll fix the Clang errors related to `Clang 13` in the same fix (without the added flags, which has its own issue)

**Closed** 2022-12-03 19:40 UTC
Labels: bug

**Comment by SSBMTonberry** [comment] 2022-12-03 19:45
@dmlary : The Clang 13 issues should now be okay. However, the issue itself is not fixed, as it seems to be caused by `PocketLzma`, which handles decompression. This is another library i maintain , so I'll create an issue in that repo and get to the bottom of the issue. As long as you are not using lzma compressed maps you will be untouched by this though.

The issue seems to occur on:
- `Clang` 11, 12 and 13 for `MacOS`
- `Clang` 12 and 13 for `Linux`.

Every other compiler seems to be untouched by this issue.
